# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_add_contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data_base import *


class Ui_add_contact(object):
    def setupUi(self, add_contact):
        add_contact.setObjectName("add_contact")
        add_contact.resize(340, 209)
        add_contact.setMaximumSize(QtCore.QSize(340, 210))
        self.buttonBox = QtWidgets.QDialogButtonBox(add_contact)
        self.buttonBox.setGeometry(QtCore.QRect(230, 170, 91, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(add_contact)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 61, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_surname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_surname.setObjectName("label_surname")
        self.verticalLayout.addWidget(self.label_surname)
        self.label_number = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_number.setObjectName("label_number")
        self.verticalLayout.addWidget(self.label_number)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(add_contact)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 10, 261, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_edit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_edit_name.setObjectName("line_edit_name")
        self.verticalLayout_3.addWidget(self.line_edit_name)
        self.line_edit_surname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_edit_surname.setObjectName("line_edit_surname")
        self.verticalLayout_3.addWidget(self.line_edit_surname)
        self.line_edit_number = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.line_edit_number.setObjectName("line_edit_number")
        self.verticalLayout_3.addWidget(self.line_edit_number)
        self.btn_ok = QtWidgets.QPushButton(add_contact)
        self.btn_ok.setGeometry(QtCore.QRect(120, 170, 93, 28))
        self.btn_ok.setDefault(True)
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(add_contact)
        self.buttonBox.rejected.connect(add_contact.reject) # type: ignore
        # self.btn_ok.clicked.connect(self.add_func) # type: ignore
        # self.namber = self.line_edit_number.paste
        # print(self.namber)
        # self.btn_ok.clicked.connect(self.line_edit_surnamse.cut) # type: ignore

        # self.btn_ok.clicked.connect(self.line_edit_name.cut) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_contact)

    def retranslateUi(self, add_contact):
        _translate = QtCore.QCoreApplication.translate
        add_contact.setWindowTitle(_translate("add_contact", "Добавить контакт"))
        self.label_name.setText(_translate("add_contact", "Имя"))
        self.label_surname.setText(_translate("add_contact", "Фамилия"))
        self.label_number.setText(_translate("add_contact", "Номер"))
        self.line_edit_name.setText(_translate("add_contact", ""))
        self.line_edit_surname.setText(_translate("add_contact", ""))
        self.line_edit_number.setText(_translate("add_contact", ""))
        self.btn_ok.setText(_translate("add_contact", "Ok"))

    def add_func(self):
        name = self.line_edit_name.text()
        self.line_edit_name.setText("")
        surname = self.line_edit_surname.text()
        self.line_edit_surname.setText("")
        number = self.line_edit_number.text()
        self.line_edit_number.setText("")

        write_contact(name, surname, number)
        # print(name, surname, number)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_contact = QtWidgets.QDialog()
    ui = Ui_add_contact()
    ui.setupUi(add_contact)
    add_contact.show()
    sys.exit(app.exec_())
