# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ph.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(247, 320)
        MainWindow.setMaximumSize(QtCore.QSize(250, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_menu = QtWidgets.QLabel(self.centralwidget)
        self.label_menu.setGeometry(QtCore.QRect(40, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(13)
        font.setStrikeOut(False)
        self.label_menu.setFont(font)
        self.label_menu.setObjectName("label_menu")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 70, 147, 205))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_redactor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_redactor.setObjectName("btn_redactor")
        self.verticalLayout.addWidget(self.btn_redactor)
        self.btn_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.btn_del = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_del.setObjectName("btn_del")
        self.verticalLayout.addWidget(self.btn_del)
        self.btn_serch = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_serch.setObjectName("btn_serch")
        self.verticalLayout.addWidget(self.btn_serch)
        self.btn_print_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_print_list.setObjectName("btn_print_list")
        self.verticalLayout.addWidget(self.btn_print_list)
        self.btn_import = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_import.setObjectName("btn_import")
        self.verticalLayout.addWidget(self.btn_import)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_redactor.clicked.connect(MainWindow.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phone_directory"))
        self.label_menu.setText(_translate("MainWindow", "Главное меню"))
        self.btn_redactor.setText(_translate("MainWindow", "Редактировать данные"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_del.setText(_translate("MainWindow", "Удалить"))
        self.btn_serch.setText(_translate("MainWindow", "Поиск"))
        self.btn_print_list.setText(_translate("MainWindow", "Вывести список"))
        self.btn_import.setText(_translate("MainWindow", "Импорт"))



