# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_redactor_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_redactor_data(object):
    def setupUi(self, win_redactor_data):
        win_redactor_data.setObjectName("win_redactor_data")
        win_redactor_data.resize(180, 200)
        win_redactor_data.setMaximumSize(QtCore.QSize(180, 200))
        self.verticalLayoutWidget = QtWidgets.QWidget(win_redactor_data)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_txt = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name_txt.setObjectName("name_txt")
        self.verticalLayout.addWidget(self.name_txt)
        self.surname_txt = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.surname_txt.setObjectName("surname_txt")
        self.verticalLayout.addWidget(self.surname_txt)
        self.number_txt = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.number_txt.setObjectName("number_txt")
        self.verticalLayout.addWidget(self.number_txt)
        self.btn_ok = QtWidgets.QPushButton(win_redactor_data)
        self.btn_ok.setGeometry(QtCore.QRect(40, 150, 93, 28))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(win_redactor_data)
        QtCore.QMetaObject.connectSlotsByName(win_redactor_data)

    def retranslateUi(self, win_redactor_data):
        _translate = QtCore.QCoreApplication.translate
        win_redactor_data.setWindowTitle(_translate("win_redactor_data", "Изменить"))
        self.btn_ok.setText(_translate("win_redactor_data", "Ок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_redactor_data = QtWidgets.QWidget()
    ui = Ui_win_redactor_data()
    ui.setupUi(win_redactor_data)
    win_redactor_data.show()
    sys.exit(app.exec_())
