# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_serch_window(object):
    def setupUi(self, serch_window):
        serch_window.setObjectName("serch_window")
        serch_window.resize(240, 320)
        self.buttonBox = QtWidgets.QDialogButtonBox(serch_window)
        self.buttonBox.setGeometry(QtCore.QRect(10, 270, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(serch_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sreach = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_sreach.setObjectName("label_sreach")
        self.horizontalLayout.addWidget(self.label_sreach)
        self.line_edit_serch = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_edit_serch.setObjectName("line_edit_serch")
        self.horizontalLayout.addWidget(self.line_edit_serch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout.addWidget(self.btn_search)
        self.result_search = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.result_search.setText("")
        self.result_search.setObjectName("result_search")
        self.verticalLayout.addWidget(self.result_search)

        self.retranslateUi(serch_window)
        self.buttonBox.accepted.connect(serch_window.accept) # type: ignore
        self.buttonBox.rejected.connect(serch_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(serch_window)

    def retranslateUi(self, serch_window):
        _translate = QtCore.QCoreApplication.translate
        serch_window.setWindowTitle(_translate("serch_window", "Найти"))
        self.label_sreach.setText(_translate("serch_window", "Значение"))
        self.btn_search.setText(_translate("serch_window", "Найти"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     serch_window = QtWidgets.QDialog()
#     ui = Ui_serch_window()
#     ui.setupUi(serch_window)
#     serch_window.show()
#     sys.exit(app.exec_())
