# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from funcs import *
from data_base import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 462)
        self.list_box = QtWidgets.QDialogButtonBox(Dialog)
        self.list_box.setGeometry(QtCore.QRect(290, 10, 80, 300))
        self.list_box.setMaximumSize(QtCore.QSize(80, 300))
        self.list_box.setOrientation(QtCore.Qt.Vertical)
        self.list_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.list_box.setObjectName("list_box")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 271, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 269, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_list = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_list.setGeometry(QtCore.QRect(0, 0, 271, 421))
        self.label_list.setMaximumSize(QtCore.QSize(271, 16777215))
        self.label_list.setText(read_contact())
        self.label_list.setObjectName("label_list")
        self.scrollArea.setWidget(self.label_list)

        self.retranslateUi(Dialog)
        self.list_box.accepted.connect(Dialog.accept) # type: ignore
        self.list_box.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Номера"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
